seo_tokens.settings:
  type: config_object
  label: 'SEO Tokens Settings'
  mapping:
    content_types:
      type: mapping
      label: 'Content Types'
      mapping:
        type:
          type: mapping
          label: 'Content Type'
          mapping:
            fallback_field_title:
              type: string
              label: 'Fallback field title'
            fallback_field_description:
              type: string
              label: 'Fallback field description'
            fallback_field_image:
              type: string
              label: 'Fallback field image'
